server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: info-service
          uri: lb://book-info-service
          predicates:
            - Path=/info/**
          filters:
            - StripPrefix=1

        - id: rating-service
          uri: lb://book-rating-service
          predicates:
            - Path=/rating/**

          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: lb://book-catalog-service
          predicates:
            - Path=/catalog/**

          filters:
            - StripPrefix=1


