server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: info-service
          uri: http://localhost:8081
          predicates:
            - Path=/info/**
          filters:
            - StripPrefix=1

        - id: rating-service
          uri: http://localhost:8082
          predicates:
            - Path=/rating/**

          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: http://localhost:8083
          predicates:
            - Path=/catalog/**

          filters:
            - StripPrefix=1


